# Generated by Django 5.0.14 on 2026-09-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
