# Generated by Django 5.0.14 on 2026-09-05 20:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0003_tareacierre'),
        ('core', '0002_usuario_totp_habilitado_usuario_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre_completo'],
                'unique_together': {('empresa', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_pago', models.DateField()),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=30)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('otros_devengados', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_devengado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salud_empleado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pension_empleado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_deducciones', models.DecimalField(decimal_places=2, max_digits=14)),
                ('neto_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salud_empleador', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pension_empleador', models.DecimalField(decimal_places=2, max_digits=14)),
                ('arl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('caja_compensacion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cesantias', models.DecimalField(decimal_places=2, max_digits=14)),
                ('intereses_cesantias', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prima', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='nomina.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_nomina', to='core.empresa')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_nomina', to='contabilidad.transaccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación de nómina',
                'verbose_name_plural': 'Liquidaciones de nómina',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('empleado', 'anio', 'mes')},
            },
        ),
    ]
