# Generated by Django 5.0.14 on 2026-09-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_tareacierre'),
        ('core', '0002_usuario_totp_habilitado_usuario_totp_secret'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('CREDITO', 'Nota crédito'), ('DEBITO', 'Nota débito')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_debito', to='core.empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_cxd', to='facturacion.factura')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_debito', to='contabilidad.transaccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota crédito/débito',
                'verbose_name_plural': 'Notas crédito/débito',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
    ]
