# Generated by Django 5.0.14 on 2026-09-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_notacreditodebito'),
        ('productos', '0002_bodega_movimientoinventario_bodega_stockporbodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaitem',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_factura', to='productos.bodega'),
        ),
    ]
