# Generated by Django 5.0.14 on 2026-09-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
        ('core', '0002_usuario_totp_habilitado_usuario_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_cierre', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Tarea de cierre',
                'verbose_name_plural': 'Tareas de cierre',
                'ordering': ['anio', 'mes', 'orden'],
                'unique_together': {('empresa', 'anio', 'mes', 'descripcion')},
            },
        ),
    ]
