# Generated by Django 5.0.14 on 2026-09-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_tareacierre'),
        ('core', '0002_usuario_totp_habilitado_usuario_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Positivo = consignación, negativo = retiro', max_digits=14)),
                ('conciliado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='core.empresa')),
                ('movimiento_contable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacion_bancaria', to='contabilidad.movimientocontable')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
