# Generated by Django 5.0.14 on 2026-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_fix_codigo_cuenta_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo'), ('ORDEN_DEUDORA', 'Cuenta de orden deudora'), ('ORDEN_ACREEDORA', 'Cuenta de orden acreedora')], max_length=15),
        ),
    ]
