# Generated by Django 5.0.14 on 2026-09-05 20:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_totp_habilitado_usuario_totp_secret'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.bodega'),
        ),
        migrations.CreateModel(
            name='StockPorBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='productos.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_por_bodega', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Stock por bodega',
                'verbose_name_plural': 'Stock por bodega',
                'unique_together': {('producto', 'bodega')},
            },
        ),
    ]
