# Generated by Django 5.0.14 on 2026-08-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=5)),
                ('numero_documento', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('AMBOS', 'Cliente y proveedor')], default='CLIENTE', max_length=10)),
                ('razon_social', models.CharField(max_length=200, verbose_name='Nombre / razón social')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['razon_social'],
            },
        ),
    ]
