# Generated by Django 5.0.14 on 2026-08-23 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='tercero',
            unique_together={('empresa', 'numero_documento')},
        ),
    ]
